services:
  db:
    image: postgres:13.20-alpine3.20
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend

  transaction-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactionApi
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge
